export const LEGACY_TEMPLATE_CATALOG = [
  {
    id: 'legacy-template-23283',
    slug: 'clipforge-ai-powered-long-to-shorts-video-engine',
    title: 'ClipForge — AI-Powered Long-to-Shorts Video Engine',
    tagline:
      'Turn long podcasts and videos into high-retention vertical shorts with an automated AI editing pipeline.',
    description:
      'ClipForge is an end-to-end AI video automation platform for creators, podcasters, and marketing teams. It transcribes source video, identifies high-retention moments, creates frame-accurate clips, reframes landscape footage into 9:16 video with face tracking, and adds animated synchronized captions.\n\nThe architecture includes a decoupled background worker pipeline, media processing, smart viral-moment scoring, and production-ready creator workflows. The downloadable project package can be attached later from the Delivery section in the admin panel.',
    thumbnail: '/assets/template-clipforge.png',
    previewUrl: 'https://clipforge.app',
    price: 399,
    currency: 'INR',
    category: 'AI Video',
    tags: ['AI', 'Video', 'Automation', 'SaaS', 'OpenAI'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: true,
  },
  {
    id: 'legacy-template-14223',
    slug: 'angular-starter-kit',
    title: 'Angular Starter Kit',
    tagline:
      'A modern Angular admin foundation with reusable dashboards, authentication, tables, forms, and reports.',
    description:
      'Angular Starter Kit is a modern frontend admin dashboard for building SaaS products, CRMs, and business portals. It uses Angular standalone architecture with Bootstrap, AdminLTE, responsive layouts, JWT-ready authentication screens, role-based UI, modular services, and reusable components.\n\nIncluded UI modules cover dashboard analytics, user and role management, country and state management, reports, filters, pagination, charts, modals, toasts, skeleton loaders, Excel and print export, WYSIWYG editing, form controls, and SCSS theming. The source package can be uploaded later from the product Delivery tab.',
    thumbnail: '/assets/template-angular-starter.png',
    previewUrl: 'https://nykz.github.io/Angular-Starter-Admin-Portal/',
    price: 4000,
    currency: 'INR',
    category: 'Angular',
    tags: ['Angular', 'Admin Panel', 'Dashboard', 'Bootstrap', 'TypeScript'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: true,
  },
  {
    id: 'legacy-template-14125',
    slug: 'angular-laravel-admin-starter-kit',
    title: 'Angular + Laravel Admin Starter Kit',
    tagline:
      'A full-stack Angular and Laravel starter for scalable dashboards, CRMs, SaaS products, and portals.',
    description:
      'This full-stack starter combines an Angular standalone frontend with a secure Laravel REST API. It includes responsive Bootstrap and AdminLTE layouts, JWT and Sanctum authentication patterns, role-based access control, CORS setup, notification and email OTP foundations, reusable validation helpers, and modular project structure.\n\nFunctional modules include dashboard analytics, user and role management, country and state CRUD, reports with filtering and Excel export, reusable form controls, tables, charts, modals, toasts, skeleton loaders, WYSIWYG editing, SCSS theming, and documented extension points.',
    thumbnail: '/assets/template-angular-laravel.png',
    previewUrl: 'https://nykz.github.io/Angular-Laravel-Starter-Admin-Panel',
    price: 6000,
    currency: 'INR',
    category: 'Full Stack',
    tags: ['Angular', 'Laravel', 'Admin Panel', 'REST API', 'RBAC'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: true,
  },
  {
    id: 'legacy-template-13992',
    slug: 'construct-kit-app-the-ultimate-construction-site-management-system',
    title: 'Construct Kit App — Construction Site Management System',
    tagline:
      'A multi-role construction operations suite for materials, machines, tools, teams, and site progress.',
    description:
      'Construct Kit centralizes construction-site operations for engineers, managers, administrators, and operations teams. The suite combines an Ionic mobile app and PWA, an Angular admin portal, Laravel APIs, and Firebase push notifications.\n\nIt covers material requests and approvals, dispatch and delivery confirmation, site inventory, dashboards, worksheets, machine usage, payment calculation, work-level progress, tool allocation and returns, multi-site switching, reports, filters, charts, and Excel export. Admin portal preview: https://technyks.com/constructkit/admin-portal',
    thumbnail: '/assets/template-construct-kit.png',
    previewUrl: 'https://technyks.com/constructkit/pwa',
    price: 16000,
    currency: 'INR',
    category: 'Business App',
    tags: ['Ionic', 'Angular', 'Laravel', 'Firebase', 'Construction'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: true,
  },
  {
    id: 'legacy-template-13638',
    slug: 'angular-admin-panel-free',
    title: 'Angular Admin Panel',
    tagline:
      'A responsive Angular dashboard UI with analytics, tables, forms, user management, and export tools.',
    description:
      'Build a polished Angular admin dashboard with responsive navigation, sales and user analytics, bar and pie charts, dynamic user and vendor management, filters, pagination, reusable components, routing, modal forms, and full-screen interactions.\n\nThe interface uses Angular Material, ngx-charts, ngx-datatable, Font Awesome, Bootstrap components, and Excel export patterns. It is suitable for ecommerce backends, SaaS dashboards, and developers learning practical admin UI architecture.',
    thumbnail: '/assets/template-angular-admin.png',
    previewUrl: null,
    price: 159,
    currency: 'INR',
    category: 'Angular',
    tags: ['Angular', 'Admin Panel', 'Analytics', 'Charts', 'Datatable'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-5005',
    slug: 'ultimate-quiz-app-ui-template-ionic-supabase',
    title: 'Ultimate Quiz App UI Template — Ionic & Supabase',
    tagline:
      'A customizable quiz-app UI with dynamic forms, spreadsheet imports, timers, scores, and leaderboards.',
    description:
      'This Ionic and Supabase-powered quiz template is designed for trivia apps, educational quiz platforms, and personality tests. It includes dynamic questionnaire forms, Excel-based question imports, responsive mobile layouts, real-time data foundations, timers, score tracking, leaderboards, and reusable quiz components.\n\nThe project is structured for easy branding and extension, helping developers and educators launch an engaging quiz experience without rebuilding common flows from scratch.',
    thumbnail: '/assets/template-quiz-app.png',
    previewUrl: null,
    price: 399,
    currency: 'INR',
    category: 'Mobile App',
    tags: ['Ionic', 'Supabase', 'Quiz', 'Excel', 'Dynamic Forms'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-4924',
    slug: 'gift-shop-app-ui-ionic-with-laravel-angular',
    title: 'Gift Shop App UI — Ionic, Laravel & Angular',
    tagline:
      'A modern cross-platform gift-store experience with mobile shopping flows and scalable administration.',
    description:
      'Gift Shop App UI is a professionally designed ecommerce foundation built with Ionic and Angular and prepared for a Laravel backend. It provides a clean, responsive customer experience for browsing gift collections, viewing products, managing a cart, and completing common shopping flows.\n\nThe interface is optimized for cross-platform use, customization, performance, and scalable data management, making it a practical starting point for gift stores and general ecommerce applications.',
    thumbnail: '/assets/template-gift-shop.png',
    previewUrl: null,
    price: 399,
    currency: 'INR',
    category: 'Ecommerce',
    tags: ['Ionic', 'Angular', 'Laravel', 'Ecommerce', 'Mobile UI'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-4559',
    slug: 'ionic-8-restaurant-food-delivery-app-ui-template',
    title: 'Ionic 8+ Restaurant Food Delivery App UI Template',
    tagline:
      'A restaurant-partner mobile UI for orders, menus, payments, analytics, delivery status, and support.',
    description:
      'This Ionic restaurant-partner template helps restaurants manage their delivery operation from a responsive mobile interface. It includes login and signup, incoming-order management, real-time status updates, sales analytics, menu tools, payment management, customer and order details, and help-chat screens.\n\nThe package is designed for Capacitor with Angular, supports standalone and NgModule approaches, and is structured for integration with the backend of your choice. Documentation and future package updates can be delivered to buyers after the source archive is attached.',
    thumbnail: '/assets/template-restaurant-delivery.png',
    previewUrl: 'https://nykz.github.io/Ionic-Restaurant-App',
    price: 3000,
    currency: 'INR',
    category: 'Food Delivery',
    tags: ['Ionic', 'Angular', 'Restaurant', 'Food Delivery', 'Capacitor'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-4558',
    slug: 'ionic-8-rider-food-delivery-app-ui-template',
    title: 'Ionic 8+ Rider Food Delivery App UI Template',
    tagline:
      'A delivery-rider mobile UI for jobs, navigation, earnings, order progress, payments, and support.',
    description:
      'This Ionic rider-side template provides the core screens for a modern delivery workforce. Riders can sign in, discover and accept delivery jobs, navigate with map-based flows, manage active orders, track earnings, view payments and delivery details, and access help-chat screens.\n\nThe responsive Capacitor and Angular codebase supports both standalone and NgModule approaches and is designed to integrate cleanly with a custom backend. Documentation and the final source package can be attached from the admin Delivery tab.',
    thumbnail: '/assets/template-rider-delivery.png',
    previewUrl: 'https://nykz.github.io/Ionic-Driver-App',
    price: 3000,
    currency: 'INR',
    category: 'Food Delivery',
    tags: ['Ionic', 'Angular', 'Rider App', 'Food Delivery', 'Capacitor'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-3392',
    slug: 'real-time-chat-app-ionic-firebase',
    title: 'Real-Time Chat App — Ionic & Firebase',
    tagline:
      'A responsive Ionic messaging UI with secure conversations, real-time updates, and Firebase integration.',
    description:
      'This feature-rich chat application template combines Ionic UI patterns with Firebase Realtime Database foundations. It is designed for responsive, real-time conversations across devices with secure instant messaging, live updates, contact and conversation views, message states, and a clean mobile-first experience.\n\nUse it as a starting point for personal messaging products, customer support chat, or professional team collaboration tools, then customize the theme and connect the final business logic to your own services.',
    thumbnail: '/assets/template-realtime-chat.png',
    previewUrl: null,
    price: 399,
    currency: 'INR',
    category: 'Mobile App',
    tags: ['Ionic', 'Firebase', 'Chat', 'Realtime', 'Mobile UI'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-3078',
    slug: 'ionic-jokar-all-in-one-delivery-dunzo-clone-app-template',
    title: 'Ionic Jokar — All-in-One Delivery App Template',
    tagline:
      'A Dunzo-style multi-category delivery UI for food, groceries, medicine, gifts, meat, pets, and courier pickup.',
    description:
      'Jokar is an all-in-one customer delivery application covering nearby shops, food, groceries, medicines, gifts, meat, pet supplies, and courier pickup. The UI includes phone and OTP access, Google Maps address flows, multi-category browsing, cart management, coupons, payments, order details, and help chat.\n\nThe responsive Ionic and Angular project supports both standalone and NgModule approaches and is structured for integration with a custom backend. It provides a practical Dunzo-style foundation with documentation and a live web preview.',
    thumbnail: '/assets/template-jokar-delivery.png',
    previewUrl: 'https://jokarapp.web.app/',
    price: 5000,
    currency: 'INR',
    category: 'Delivery App',
    tags: ['Ionic', 'Angular', 'Delivery', 'Marketplace', 'Capacitor'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-38',
    slug: 'ionic-customer-food-delivery-app-ui-template-standalone-ngmodule',
    title: 'Ionic 8+ Customer Food Delivery App UI Template',
    tagline:
      'A polished customer-side food-delivery UI for restaurants, addresses, cart, coupons, payments, and orders.',
    description:
      'This Ionic customer application provides the essential screens for a multi-restaurant food-delivery service. It includes login and signup, restaurant and menu discovery, Google Maps address management, cart flows, coupons and promotions, payments, order details, and accessible help chat.\n\nThe responsive Capacitor and Angular source supports both standalone and NgModule approaches, includes documentation, and is structured for easy integration with any backend technology.',
    thumbnail: '/assets/template-customer-food-delivery.png',
    previewUrl: 'https://maza-eats-ui-app.web.app/',
    price: 3000,
    currency: 'INR',
    category: 'Food Delivery',
    tags: ['Ionic', 'Angular', 'Customer App', 'Food Delivery', 'Capacitor'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: false,
  },
  {
    id: 'legacy-template-27',
    slug: 'ionic-8-food-delivery-apps-angular-19-admin-panel-with-firebase',
    title: 'Ionic Food Delivery Suite + Angular Admin & Firebase',
    tagline:
      'A complete multi-restaurant platform with customer, restaurant, rider, and Angular administration apps.',
    description:
      'This full food-delivery suite includes customer, restaurant-partner, and rider applications plus an Angular admin portal and Firebase backend. It supports Android, iOS, and PWA delivery experiences, multiple restaurants, payment gateways, geolocation addresses, live tracking, push notifications, reports, payouts, cash collection, automated revenue-share calculations, configurable delivery fares, and restaurant, food, and driver reviews.\n\nThe package includes both standalone and NgModule Ionic applications, the admin panel, installation guidance, documentation, APK delivery options, and update-ready project structure. Additional previews: restaurant https://nykz.github.io/Ionic-Restaurant-App and rider https://nykz.github.io/Ionic-Driver-App.',
    thumbnail: '/assets/template-food-delivery-suite.png',
    previewUrl: 'https://mazaeatsportal.web.app/',
    price: 16000,
    currency: 'INR',
    category: 'Full Stack',
    tags: ['Ionic', 'Angular', 'Firebase', 'Food Delivery', 'Admin Panel'],
    filePath: null,
    fileName: null,
    fileSize: null,
    deliveryUrl: null,
    downloadButtonText: 'Download source files',
    buyerMessage: null,
    isPublished: true,
    isFeatured: true,
  },
];
