// GENERATED by scripts/generate-bootstrap-schema.cjs from prisma/schema.prisma.
// Do not edit by hand; re-run the script after changing the Prisma schema.

export const BOOTSTRAP_TABLES: { name: string; sql: string }[] = [
  {
    "name": "User",
    "sql": "CREATE TABLE `User` (\n    `id` VARCHAR(191) NOT NULL,\n    `email` VARCHAR(191) NOT NULL,\n    `passwordHash` VARCHAR(191) NULL,\n    `googleId` VARCHAR(191) NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `avatarUrl` VARCHAR(191) NULL,\n    `role` ENUM('STUDENT', 'ADMIN') NOT NULL DEFAULT 'STUDENT',\n    `onboardingCompleted` BOOLEAN NOT NULL DEFAULT false,\n    `learnerGoal` VARCHAR(191) NULL,\n    `experienceLevel` VARCHAR(191) NULL,\n    `membershipPreference` VARCHAR(191) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `User_email_key`(`email`),\n    UNIQUE INDEX `User_googleId_key`(`googleId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Course",
    "sql": "CREATE TABLE `Course` (\n    `id` VARCHAR(191) NOT NULL,\n    `slug` VARCHAR(191) NOT NULL,\n    `title` VARCHAR(191) NOT NULL,\n    `subtitle` VARCHAR(191) NOT NULL,\n    `description` TEXT NOT NULL,\n    `thumbnail` VARCHAR(191) NULL,\n    `promoVideoUrl` TEXT NULL,\n    `price` DOUBLE NOT NULL,\n    `isFree` BOOLEAN NOT NULL DEFAULT false,\n    `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',\n    `level` VARCHAR(191) NOT NULL DEFAULT 'Intermediate',\n    `category` VARCHAR(191) NOT NULL DEFAULT 'Web Development',\n    `isPublished` BOOLEAN NOT NULL DEFAULT false,\n    `isArchived` BOOLEAN NOT NULL DEFAULT false,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Course_slug_key`(`slug`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Module",
    "sql": "CREATE TABLE `Module` (\n    `id` VARCHAR(191) NOT NULL,\n    `courseId` VARCHAR(191) NOT NULL,\n    `title` VARCHAR(191) NOT NULL,\n    `order` INTEGER NOT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Lesson",
    "sql": "CREATE TABLE `Lesson` (\n    `id` VARCHAR(191) NOT NULL,\n    `moduleId` VARCHAR(191) NOT NULL,\n    `title` VARCHAR(191) NOT NULL,\n    `description` TEXT NULL,\n    `videoAssetRef` VARCHAR(191) NULL,\n    `duration` INTEGER NOT NULL DEFAULT 0,\n    `order` INTEGER NOT NULL,\n    `isFreePreview` BOOLEAN NOT NULL DEFAULT false,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Enrollment",
    "sql": "CREATE TABLE `Enrollment` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `courseId` VARCHAR(191) NOT NULL,\n    `progressPercent` DOUBLE NOT NULL DEFAULT 0.0,\n    `lastWatchedLessonId` VARCHAR(191) NULL,\n    `completedLessonIds` JSON NOT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Enrollment_userId_courseId_key`(`userId`, `courseId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Review",
    "sql": "CREATE TABLE `Review` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `courseId` VARCHAR(191) NOT NULL,\n    `rating` INTEGER NOT NULL,\n    `comment` TEXT NOT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    INDEX `Review_courseId_createdAt_idx`(`courseId`, `createdAt`),\n    UNIQUE INDEX `Review_userId_courseId_key`(`userId`, `courseId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "MembershipPlan",
    "sql": "CREATE TABLE `MembershipPlan` (\n    `id` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `slug` VARCHAR(191) NOT NULL,\n    `description` TEXT NULL,\n    `price` DOUBLE NOT NULL,\n    `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',\n    `interval` ENUM('MONTHLY', 'ANNUAL') NOT NULL,\n    `isFree` BOOLEAN NOT NULL DEFAULT false,\n    `isActive` BOOLEAN NOT NULL DEFAULT true,\n    `accessAllCourses` BOOLEAN NOT NULL DEFAULT true,\n    `features` JSON NOT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `MembershipPlan_slug_key`(`slug`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "MembershipCourseAccess",
    "sql": "CREATE TABLE `MembershipCourseAccess` (\n    `planId` VARCHAR(191) NOT NULL,\n    `courseId` VARCHAR(191) NOT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `MembershipCourseAccess_courseId_idx`(`courseId`),\n    PRIMARY KEY (`planId`, `courseId`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Subscription",
    "sql": "CREATE TABLE `Subscription` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `planId` VARCHAR(191) NOT NULL,\n    `status` ENUM('ACTIVE', 'CANCELED', 'PAST_DUE', 'EXPIRED') NOT NULL DEFAULT 'ACTIVE',\n    `currentPeriodStart` DATETIME(3) NOT NULL,\n    `currentPeriodEnd` DATETIME(3) NOT NULL,\n    `razorpaySubscriptionId` VARCHAR(191) NULL,\n    `lemonSqueezySubscriptionId` VARCHAR(191) NULL,\n    `cancelAtPeriodEnd` BOOLEAN NOT NULL DEFAULT false,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Coupon",
    "sql": "CREATE TABLE `Coupon` (\n    `id` VARCHAR(191) NOT NULL,\n    `code` VARCHAR(191) NOT NULL,\n    `discountPercent` DOUBLE NULL,\n    `discountAmount` DOUBLE NULL,\n    `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',\n    `scope` VARCHAR(191) NOT NULL DEFAULT 'COURSE',\n    `courseId` VARCHAR(191) NULL,\n    `templateProductId` VARCHAR(191) NULL,\n    `expiryDate` DATETIME(3) NULL,\n    `usageLimit` INTEGER NULL,\n    `timesUsed` INTEGER NOT NULL DEFAULT 0,\n    `isActive` BOOLEAN NOT NULL DEFAULT true,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Coupon_code_key`(`code`),\n    INDEX `Coupon_templateProductId_idx`(`templateProductId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Certificate",
    "sql": "CREATE TABLE `Certificate` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `courseId` VARCHAR(191) NOT NULL,\n    `certificateNumber` VARCHAR(191) NOT NULL,\n    `pdfUrl` VARCHAR(191) NOT NULL,\n    `issuedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    UNIQUE INDEX `Certificate_certificateNumber_key`(`certificateNumber`),\n    UNIQUE INDEX `Certificate_userId_courseId_key`(`userId`, `courseId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "Payment",
    "sql": "CREATE TABLE `Payment` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `amount` DOUBLE NOT NULL,\n    `currency` VARCHAR(191) NOT NULL,\n    `status` ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'PENDING',\n    `provider` ENUM('RAZORPAY', 'LEMON_SQUEEZY') NOT NULL,\n    `paymentIntentId` VARCHAR(191) NULL,\n    `subscriptionId` VARCHAR(191) NULL,\n    `planId` VARCHAR(191) NULL,\n    `courseId` VARCHAR(191) NULL,\n    `templateProductIds` JSON NULL,\n    `couponCode` VARCHAR(191) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Payment_paymentIntentId_key`(`paymentIntentId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "UiTemplate",
    "sql": "CREATE TABLE `UiTemplate` (\n    `id` VARCHAR(191) NOT NULL,\n    `slug` VARCHAR(191) NOT NULL,\n    `title` VARCHAR(191) NOT NULL,\n    `tagline` VARCHAR(191) NOT NULL,\n    `description` TEXT NOT NULL,\n    `thumbnail` TEXT NULL,\n    `promoVideoUrl` TEXT NULL,\n    `previewUrl` TEXT NULL,\n    `price` DOUBLE NOT NULL,\n    `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',\n    `category` VARCHAR(191) NOT NULL DEFAULT 'Website UI',\n    `tags` JSON NOT NULL,\n    `filePath` TEXT NULL,\n    `fileName` VARCHAR(191) NULL,\n    `fileSize` INTEGER NULL,\n    `deliveryUrl` TEXT NULL,\n    `downloadButtonText` VARCHAR(191) NOT NULL DEFAULT 'Download files',\n    `buyerMessage` TEXT NULL,\n    `isPublished` BOOLEAN NOT NULL DEFAULT false,\n    `isFeatured` BOOLEAN NOT NULL DEFAULT false,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `UiTemplate_slug_key`(`slug`),\n    INDEX `UiTemplate_isPublished_createdAt_idx`(`isPublished`, `createdAt`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "UiTemplatePurchase",
    "sql": "CREATE TABLE `UiTemplatePurchase` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `productId` VARCHAR(191) NOT NULL,\n    `amount` DOUBLE NOT NULL,\n    `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',\n    `paymentId` VARCHAR(191) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `UiTemplatePurchase_createdAt_idx`(`createdAt`),\n    UNIQUE INDEX `UiTemplatePurchase_userId_productId_key`(`userId`, `productId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "ContactMessage",
    "sql": "CREATE TABLE `ContactMessage` (\n    `id` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `email` VARCHAR(191) NOT NULL,\n    `subject` VARCHAR(191) NOT NULL,\n    `message` TEXT NOT NULL,\n    `status` VARCHAR(191) NOT NULL DEFAULT 'NEW',\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    INDEX `ContactMessage_createdAt_idx`(`createdAt`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "SiteSetting",
    "sql": "CREATE TABLE `SiteSetting` (\n    `key` VARCHAR(191) NOT NULL,\n    `value` JSON NOT NULL,\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    PRIMARY KEY (`key`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "CourseQuestion",
    "sql": "CREATE TABLE `CourseQuestion` (\n    `id` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `courseId` VARCHAR(191) NOT NULL,\n    `lessonId` VARCHAR(191) NULL,\n    `title` VARCHAR(191) NOT NULL,\n    `body` TEXT NOT NULL,\n    `status` VARCHAR(191) NOT NULL DEFAULT 'OPEN',\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    INDEX `CourseQuestion_courseId_createdAt_idx`(`courseId`, `createdAt`),\n    INDEX `CourseQuestion_lessonId_idx`(`lessonId`),\n    INDEX `CourseQuestion_status_idx`(`status`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "CourseReply",
    "sql": "CREATE TABLE `CourseReply` (\n    `id` VARCHAR(191) NOT NULL,\n    `questionId` VARCHAR(191) NOT NULL,\n    `userId` VARCHAR(191) NOT NULL,\n    `body` TEXT NOT NULL,\n    `isInstructor` BOOLEAN NOT NULL DEFAULT false,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    INDEX `CourseReply_questionId_createdAt_idx`(`questionId`, `createdAt`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  },
  {
    "name": "CourseAnnouncement",
    "sql": "CREATE TABLE `CourseAnnouncement` (\n    `id` VARCHAR(191) NOT NULL,\n    `createdById` VARCHAR(191) NOT NULL,\n    `title` VARCHAR(191) NOT NULL,\n    `body` TEXT NOT NULL,\n    `targetCourseIds` JSON NOT NULL,\n    `sendEmail` BOOLEAN NOT NULL DEFAULT false,\n    `emailStatus` VARCHAR(191) NOT NULL DEFAULT 'NOT_REQUESTED',\n    `recipientCount` INTEGER NOT NULL DEFAULT 0,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    INDEX `CourseAnnouncement_createdAt_idx`(`createdAt`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
  }
];

export const BOOTSTRAP_FOREIGN_KEYS: { table: string; sql: string }[] = [
  {
    "table": "Module",
    "sql": "ALTER TABLE `Module` ADD CONSTRAINT `Module_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Lesson",
    "sql": "ALTER TABLE `Lesson` ADD CONSTRAINT `Lesson_moduleId_fkey` FOREIGN KEY (`moduleId`) REFERENCES `Module`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Enrollment",
    "sql": "ALTER TABLE `Enrollment` ADD CONSTRAINT `Enrollment_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Enrollment",
    "sql": "ALTER TABLE `Enrollment` ADD CONSTRAINT `Enrollment_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Review",
    "sql": "ALTER TABLE `Review` ADD CONSTRAINT `Review_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Review",
    "sql": "ALTER TABLE `Review` ADD CONSTRAINT `Review_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "MembershipCourseAccess",
    "sql": "ALTER TABLE `MembershipCourseAccess` ADD CONSTRAINT `MembershipCourseAccess_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `MembershipPlan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "MembershipCourseAccess",
    "sql": "ALTER TABLE `MembershipCourseAccess` ADD CONSTRAINT `MembershipCourseAccess_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Subscription",
    "sql": "ALTER TABLE `Subscription` ADD CONSTRAINT `Subscription_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Subscription",
    "sql": "ALTER TABLE `Subscription` ADD CONSTRAINT `Subscription_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `MembershipPlan`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE"
  },
  {
    "table": "Coupon",
    "sql": "ALTER TABLE `Coupon` ADD CONSTRAINT `Coupon_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE SET NULL ON UPDATE CASCADE"
  },
  {
    "table": "Coupon",
    "sql": "ALTER TABLE `Coupon` ADD CONSTRAINT `Coupon_templateProductId_fkey` FOREIGN KEY (`templateProductId`) REFERENCES `UiTemplate`(`id`) ON DELETE SET NULL ON UPDATE CASCADE"
  },
  {
    "table": "Certificate",
    "sql": "ALTER TABLE `Certificate` ADD CONSTRAINT `Certificate_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Certificate",
    "sql": "ALTER TABLE `Certificate` ADD CONSTRAINT `Certificate_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Payment",
    "sql": "ALTER TABLE `Payment` ADD CONSTRAINT `Payment_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "Payment",
    "sql": "ALTER TABLE `Payment` ADD CONSTRAINT `Payment_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE SET NULL ON UPDATE CASCADE"
  },
  {
    "table": "UiTemplatePurchase",
    "sql": "ALTER TABLE `UiTemplatePurchase` ADD CONSTRAINT `UiTemplatePurchase_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "UiTemplatePurchase",
    "sql": "ALTER TABLE `UiTemplatePurchase` ADD CONSTRAINT `UiTemplatePurchase_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `UiTemplate`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE"
  },
  {
    "table": "CourseQuestion",
    "sql": "ALTER TABLE `CourseQuestion` ADD CONSTRAINT `CourseQuestion_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "CourseQuestion",
    "sql": "ALTER TABLE `CourseQuestion` ADD CONSTRAINT `CourseQuestion_courseId_fkey` FOREIGN KEY (`courseId`) REFERENCES `Course`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "CourseReply",
    "sql": "ALTER TABLE `CourseReply` ADD CONSTRAINT `CourseReply_questionId_fkey` FOREIGN KEY (`questionId`) REFERENCES `CourseQuestion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "CourseReply",
    "sql": "ALTER TABLE `CourseReply` ADD CONSTRAINT `CourseReply_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  },
  {
    "table": "CourseAnnouncement",
    "sql": "ALTER TABLE `CourseAnnouncement` ADD CONSTRAINT `CourseAnnouncement_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE"
  }
];
